module.exports = {

  FETCH_COMMENTS: 'FETCH_COMMENTS',
  RECEIVE_COMMENTS: 'RECEIVE_COMMENTS',

  FETCH_PARENT_COMMENT:'FETCH_PARENT_COMMENT',
  RECEIVE_PARENT_COMMENT: 'RECEIVE_PARENT_COMMENT',

  CHANGE_FILTER: 'CHANGE_FILTER',
  SELECT_COMMENT: 'SELECT_COMMENT',

  NEXT_COMMENT:'NEXT_COMMENT',
  PREV_COMMENT: 'PREV_COMMENT'
}
